#!/bin/bash

set -u

docker build -f "$DOCKERFILE_PATH" --label org.opencontainers.image.revision="$SOURCE_COMMIT" --label org.opencontainers.image.build-date="$(date --rfc-3339=seconds)" --label org.opencontainers.image.version="$DOCKER_TAG" -t "$IMAGE_NAME" .
